### ISSUE TITLE
Re: Problems with `clap` and other parsers

### ISSUE THREAD

**Issue by pacak** [tertsdiepraam/uutils-args#17]
bpaf author here, always looking to improve the library :)

> Problem 1: No many-to-many relationship between arguments and settings

> This is the biggest issue we have with `clap`. In `clap`, it is assumed that options do not interfere with each other. This means that partially overriding options are really hard to support. 

My `rm`-fu is insufficient to know the difference between two invocations given below, but in `bpaf` interaction between options is possible. If you want to apply different rules for `--interactive=never` iff `-f` is present you can do something like this:

```rust
// define two variants of `--interactive` parsers, parsed types must be the same but for purposes of this example there's no other restrictions

let int_w = ... // impl Parser<Interactive>, parser to use where `--force` is present
let int_wo = ... // impl Parser<Interactive>, parser to use otherwise

let force = short('f').req_flag(true); // impl Parser<bool>, succeeds only when `-f` is passed
let with = construct!(force, interactive_with); // impl Parser<bool, Interactive>
let no_force = pure(false);
let without = construct!(no_force, int_wo); // impl Parser<bool, Interactive>, ignores `-f` and will succeed for as long as `int_wo` succeeds

// this parser will use different parsers for `--interactive` depending on if `--force` is present or not.
let combined = construct!([with, without]); // impl Parser<bool, Interactive>
```

Is something missing here?

> Problem 2: We can't use the derive API
> but that feels overly complicated. 

I usually mix derive and combinatoric APIs (derive API in bpaf is just some syntactic sugar for combinatoric API anyway), a good example is here: https://github.com/pacak/cargo-show-asm/blob/master/src/opts.rs

> Problem 4: Subtle differences

> But even then, there is no way to tell clap to consider the = as part of the value.

`any` + `anywhere` + `parse` gives you a chance to parse anything anywhere. If you have multiple such fields you can just define your own primitive - see example for `dd` that defines `tag` function.

> Problem 5: Deprecated syntax of head, tail and uniq

> e.g. `-5` is short for `-s 5`

Same `any` + `anywhere` + `parse`, you can combine it alternatively with a parser that accepts plain `-s 5` so application gets just one value for input.

> Problem 6: Exit codes

> In coreutils, different utils have different exit codes when they fail to parse.

`Args::from` + `OptionParser::run_inner` - any exit code should be possible.

> Problem 6: It's stringly typed

Not bpaf :)

> Problem 7: Reading help string from a file

In combinatoric API `.help` is a plain function that takes anything that can be converted to a string.

> Problem 8: No markdown support

That's interestring, I'm implementing support for generating manpages and markdown documentation from right now...

     

> Other parsers
> [bpaf](https://github.com/pacak/bpaf)

> Very configurable, even supports dd-style.

Interestingly enough I don't see it as configurable but flexible. There's no predefined configurations, you create parsers from available primitives using applicatives and the limit is only how far you can get with applicative/alternative functors (pretty far).

> No different configuration between short and long options (as far as I can find).

Can you expand a bit on this?

> Does not have the many-to-many relationship (options map directly to fields in a struct).

Options map to a computation tree. I tried to give an example of my understanding of a problem. If that's my misunderstanding - I can give one more go :)

**Comment by tertsdiepraam** [comment]
Hi! Thanks for your input!

First of all, in that document I focused mainly on clap and looked at all the other parser much less in depth and mostly tried to find deal breakers, i.e. properties of the library that would not make it suitable. I wrote those comments based on an admittedly quite shallow understanding of the library.

> Is something missing here?

I'm not sure. I don't need different parsers, but I need arguments to apply changes to multiple settings. Let me try to illustrate it with a simpler example:
```rust
let a = false;
let b = false;
// `--foo` sets a = true,
// `--bar` sets a = true and b = true
// `--baz` sets a = false
```
Is that supported by bpaf?

> I usually mix derive and combinatoric APIs (derive API in bpaf is just some syntactic sugar for combinatoric API anyway),

It's very nice that the combination of derive and combinatoric is so easy to do!

>> Problem 7: Reading help string from a file
>
> In combinatoric API .help is a plain function that takes anything that can be converted to a string.

Clap works the same way, but I'd like to make this easier, especially because I want to do the parsing of the file at compile time).

> Interestingly enough I don't see it as configurable but flexible.

Agreed, that's a better term :)

However, the flexibility would probably require us to make some library on top of bpaf to provide some coreutils-specific defaults, even if that library would be smaller that what I'm currently writing in this repo.

> > No different configuration between short and long options (as far as I can find).
>
> Can you expand a bit on this?

There are a couple different cases where a value can be passed to a long argument and but not to the short argument. Or where the value is optional for the long argument but required for the short argument. So we need to be able to specify for the short and long argument separately whether the argument can be passed and is required. But we still want them to be unified in the help text. See the cases here: https://github.com/tertsdiepraam/uutils-args/blob/main/design/arguments_in_coreutils.md#options-with-values

**Comment by pacak** [comment]
> Is that supported by bpaf?
```rust
let a = false;
let b = false;
// `--foo` sets a = true,
// `--bar` sets a = true and b = true
// `--baz` sets a = false <- I'm assuming this sets b=true
if they are mutually exclusive you can do this:
let foo = long("foo").req_flag((true, false));
let bar = long("bar").req_flag((true, true));
let baz = long("baz").req_flag((false, true));
let res = construct!([foo, bar, baz]); // impl Parser<(bool, bool)>
```

At this point you can use `res` to assign a pair of bools. `--foo`, `--bar` and `--baz` are mutually exclusive at this point and at least one is required, but you can change the behavior further with `fallback` or using `many` and picking the last variant to allow subsequent flags to override the behavior.

> Clap works the same way, but I'd like to make this easier, especially because I want to do the parsing of the file at compile time).

If you want to parse just help strings - there's `include_str!`.

> However, the flexibility would probably require us to make some library on top of bpaf to provide some coreutils-specific defaults, 

True. `bpaf` comes with dynamic shell completion and other goodies though :) Plus if there's an interest - I can port some of the cases in "batteries" module and implement the rest with public API.

> So we need to be able to specify for the short and long argument separately whether the argument can be passed and is required. But we still want them to be unified in the help text.

You make separate versions of short and long arguments with any requirements you want, they need to return the same type and make them hidden. Then you make an option that combines both short and long names and use `parse` to make it fail. Then you combine all 3 options with `construct!([a, b, c])`. First two will be used for actual parsing, last one will be used to display help information and auto completion.

```rust
let a = short('f').req_flag(None).hide();
let b = long("classify").argument("WHEN").map(Some).hide();
let c = short('f').long("classify").argument("WHEN").parse(|_| Err("nope"));
let res = construct!([a, b, c]); // impl Parser<Option<String>>
```

> See the cases here: https://github.com/tertsdiepraam/uutils-args/blob/main/design/arguments_in_coreutils.md#options-with-values

That's a goldmine for my unusual examples page :)

**Comment by tertsdiepraam** [comment]
They're not mutually exclusive. So when I specified only `a` it should not change `b`. That's what makes it so tricky. The obly way I found in clap is to compare the indices of the arguments.

> If you want to parse just help strings - there's include_str!.

I know, but I wanted to some filtering and parsing on it too. For example include only one section of a markdown document.

> True. bpaf comes with dynamic shell completion and other goodies though :)

That's fair :)

> Then you make an option that combines both short and long names and use parse to make it fail.

Cool! Though it's quite an elaborate workaround, it's nice to see that it's possible.

**Comment by pacak** [comment]
> I forgot to mention some important parts in the example. 

Can you give me an example in terms of existing command line tool and list some combinations and behaviors you want to achieve I can replicate?

> Though it's quite an elaborate workaround

It is really not, at most it is unconventional. I took your description and translated it mostly 1:1: 

> So we need to be able to specify for the short and long argument separately 

basically first two options defined separately

> whether the argument can be passed and is required. 

`req_flag` and `argument` bits

> But we still want them to be unified in the help text.

two `hide` modifiers and help only version. Plus "we want all 3 behaviors".

**Comment by tertsdiepraam** [comment]
> Can you give me an example in terms of existing command line tool and list some combinations and behaviors you want to achieve I can replicate?

Sure! In `ls` there are
- `-o` which sets the format to `long` and hides the group,
- `-C` sets the format to columns, and
- `-l` sets the format to long.

but the hiding of the group is not changed by `-C` and `-l`, so `ls -oCl` is the same as `ls -o` but `ls -oC` is the default column format.

> elaborate

Elaborate might not have been the right word. Unconventional / unintuitive might indeed be better.

What I'm doing in this library is to make the programmer explicitly state the argument for both the short and long variant separately. The formats are:
```rust
// arg: none, optional, required
// short: "-f", "-f[VAL]", "-f VAL"
// long: "--foo", "--foo[=VAL]", "--foo=VAL"
// So no short value and optional long val is
#[option("-f", "--foo[=VAL]")]
```

**Comment by pacak** [comment]
> Sure! In `ls` there are

I'm also assuming later flag override previous flags. I'd do something like this:
```rust
#[derive(Debug, Clone, Copy)]
enum Format {
    Columns,
    Long,
    Short,
}

fn format_and_groups_state() -> impl Parser<(Format, bool)> {
    use Format::*;
    let g = short('G').help("no group").req_flag((None, Some(false)));
    let c = short('c').help("format is columns").req_flag((Some(Columns), None));
    let l = short('l').help("format is long").req_flag((Some(Long), None));
    let o = short('o').help("format is long and no group").req_flag((Some(Long), Some(false));

    construct!([g, c, l, o]) // this accepts any parser listed above, but only one of them
        .many() // accepts all the parser listed above, collects them 
                // into a vector in the order they are given on a command line
        .map(|xs| {
            let format = xs.iter().fold_map(|x| x.0).last().unwrap_or(Short);
            let groups = xs.iter().fold_map(|x| x.1).last().unwrap_or(false);
            (format, groups)
        })
}
```

Then you plug this parser where you want to have those options.
Maybe not quite conventional, but all this really is is a table that lists flags and what columns it affects and something that collects the results.

Anyway, if you ever interested in giving `bpaf` a go - feel free to drop me a message. And we can probably close this ticket.

**Comment by tertsdiepraam** [comment]
Alright, thanks! I'll continue with my current approach to see where it will lead. I'm impressed with bpaf though, it looks very powerful.

**Comment by tertsdiepraam** [comment]
Progress has been slow on my side, I'm afraid. But I want to pick this up again soon. If you want corner cases, you might want to look at the tests in this repo. I've tried to take some of the hardest coreutils and implement their argument parsing.

I'll also take a loop at the improvements to `bpaf`, they sound great. I think `bpaf` is and will stay the better than this library for general purpose argument parsing. it might be interesting to see if I can use `bpaf` as a "backend" instead of lexopt, so I can use the error messages, manpages, etc. 🤔

**Comment by pacak** [comment]
Interesting examples, came up with something like this: https://github.com/pacak/bpaf/blob/rc-0.9.0/examples/coreutils.rs

Planning to revisit and finish them before releasing, going to merge some of the useful patterns into the library itself - `last` for example.

**Comment by tertsdiepraam** [comment]
Looks cool! I quite like how you've done `cat` with the overlapping options.
